---
# podman_nginx/tasks/main.yml

- name: "Include tasks for rootless container"
  ansible.builtin.include_tasks:
    file: rootless_container.yml
  when:
    - not podman_nginx_rootful_container | bool

- name: "Include tasks for rootful container"
  ansible.builtin.include_tasks:
    file: rootful_container.yml
    apply:
      become: true
  when:
    - podman_nginx_rootful_container | bool
